#!/bin/sh

apt-get install -y software-properties-common
add-apt-repository -y ppa:neovim-ppa/stable
apt-get update
apt-get install -y neovim

apt-get install -y stow git tmux zsh vim bzr python3-pip ranger exuberant-ctags ipython sshfs rsync autossh python-pygments irssi xclip python3-ipykernel jupyter-core jupyter-console

curl https://sh.rustup.rs -sSf | sh
cargo install tmux-hints
