#!/bin/sh
./install_packages

mkdir temp; cd temp;

wget https://bitbucket.org/melek/dmenu2/get/36cb94a16edf.zip
unzip 36cb94a16edf.zip
cd melek-dmenu2-36cb94a16edf
apt-get install -y libx11-dev libxft-dev
sed -i 's/^XINERAMA/#XINERAMA/' config.mk
make install clean
cd ..

git clone https://github.com/lutostag/yboomy.git
cd yboomy
make install
cd ..
cd ..; rm -fr temp


apt-add-repository -y ppa:qos/pulseaudio-dlna
apt-get update
apt-get install -y network-manager-openvpn-gnome redshift-gtk variety chromium-browser pepperflashplugin-nonfree lxd vlc mpv caffeine pulseaudio-dlna compiz-plugins compizconfig-settings-manager
