#!/bin/sh

apt-get install -y software-properties-common
add-apt-repository -y ppa:neovim-ppa/stable
apt-get update
apt-get install -y neovim

apt-get install -y stow git tmux zsh vim ranger exuberant-ctags ipython sshfs rsync autossh python-pygments xclip curl

curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
curl https://sh.rustup.rs -sSf | sh

cargo install tmux-hints
cargo install ripgrep
cargo install fd-find
cargo install exa
